CREATE TABLE user (
    username VARCHAR(20) PRIMARY KEY ,
    password VARCHAR(300) NOT NULL ,
    full_name VARCHAR(100) NOT NULL
);

ALTER TABLE user MODIFY COLUMN username VARCHAR(100);
ALTER TABLE user DROP COLUMN mode;